ci coverage config

diff --git a/.github/workflows/back-test-coverage.yml b/.github/workflows/back-test-coverage.yml
--- a/.github/workflows/back-test-coverage.yml
+++ b/.github/workflows/back-test-coverage.yml
@@ -21,4 +21,9 @@ jobs:
       - name: Run backend tests with coverage
         working-directory: Backend
         run: |
-          npm run test:coverage | grep -q 'Jest: "global" coverage threshold for' && exit 1)
+          if npm run test:coverage | grep -q 'Jest: "global" coverage threshold for'; then
+            echo "Error: Global coverage threshold found";
+            exit 1;
+          else
+            echo "No global coverage threshold found, proceeding...";
+          fi
diff --git a/.github/workflows/front-test-coverage.yml b/.github/workflows/front-test-coverage.yml
--- a/.github/workflows/front-test-coverage.yml
+++ b/.github/workflows/front-test-coverage.yml
@@ -21,4 +21,9 @@ jobs:
       - name: Check frontend coverage
         working-directory: Frontend/itmo_board_frontend
         run: |
-          npm run test:coverage | grep -q 'Jest: "global" coverage threshold for' && exit 1)
+          if npm run test:coverage | grep -q 'Jest: "global" coverage threshold for'; then
+            echo "Error: Global coverage threshold found";
+            exit 1;
+          else
+            echo "No global coverage threshold found, proceeding...";
+          fi
