ci config

diff --git a/.github/workflows/back-test-coverage.yml b/.github/workflows/back-test-coverage.yml
--- a/.github/workflows/back-test-coverage.yml
+++ b/.github/workflows/back-test-coverage.yml
@@ -18,12 +18,12 @@ jobs:
         working-directory: Backend
         run: npm ci
       
-      - name: Run backend tests with coverage
+      - name: Check for global coverage threshold message
         working-directory: Backend
         run: |
-          if npm run test:coverage | grep -q 'Jest: "global" coverage threshold for'; then
-            echo "Error: Global coverage threshold found";
-            exit 1;
+          if npm run test:coverage 2>&1 | grep -qE 'coverage threshold for'; then
+            echo "Error: Global coverage threshold not met";
           else
-            echo "No global coverage threshold found, proceeding...";
+            echo "Global coverage threshold met, proceeding...";
+            exit 1;
           fi
diff --git a/.github/workflows/front-test-coverage.yml b/.github/workflows/front-test-coverage.yml
--- a/.github/workflows/front-test-coverage.yml
+++ b/.github/workflows/front-test-coverage.yml
@@ -1,4 +1,4 @@
-name: Backend coverage
+name: Frontend coverage
 on:
   push:
   pull_request:
@@ -18,12 +18,12 @@ jobs:
         working-directory: Frontend/itmo_board_frontend
         run: npm ci
 
-      - name: Check frontend coverage
+      - name: Check for global coverage threshold message
         working-directory: Frontend/itmo_board_frontend
         run: |
-          if npm run test:coverage | grep -q 'Jest: "global" coverage threshold for'; then
-            echo "Error: Global coverage threshold found";
-            exit 1;
+          if npm run test:coverage 2>&1 | grep -qE 'coverage threshold for'; then
+            echo "Error: Global coverage threshold not met";
           else
-            echo "No global coverage threshold found, proceeding...";
+            echo "Global coverage threshold met, proceeding...";
+            exit 1;
           fi
